# Site settings
name:  NASA GRC Web Design Standards Documentation
version: 1.0.0
permalink: pretty
google_analytics_ua: UA-48605964-43

baseurl: /web-design-standards-docs

encoding: utf-8

jekyll_get:
  - data: releases
    json: 'https://api.github.com/repos/bruffridge/web-design-standards/releases'
  - data: contributing
    json: 'https://api.github.com/repos/18F/web-design-standards/contents/CONTRIBUTING.md'

repos:
- name: NASA Web Design Standards
  description: Main repository for the NASA Web Design Standards package
  url: https://github.com/bruffridge/web-design-standards
- name: NASA Web Design Standards Documentation
  description: Documentation for the NASA Web Design Standards
  url: https://github.com/bruffridge/web-design-standards-docs
- name: U.S. Web Design Standards Assets
  description: U.S. Web Design Standards visual design assets
  url: https://github.com/18F/web-design-standards-assets

sass:
  load_paths:
    - css
    - assets/css

collections:
  components:
    output: true
    permalink: /:path/

defaults:
  - scope:
      path: ''
      type: components
    values:
      layout: component

# Build settings
markdown: redcarpet
redcarpet:
  extensions:
    - tables
    - with_toc_data # automatic heading ids

gems:
  - jekyll-redirect-from

exclude:
- ".ruby-version"
- ".sass-cache"
- CONTRIBUTING.md
- Gemfile
- Gemfile.lock
- LICENSE.md
- README.md
- "config/*"
- "js/*"
- manifest.yml
- node_modules
- package.json
- "vendor/*"
- gulpfile.js
- circle.yml
