# Site settings
title:  NASA Glenn Web Design System
description: Design and build fast, accessible, mobile-friendly NASA websites backed by user research.
components_url: 'https://components.designsystem.digital.gov'

# this is for pages that don't have a permalink (primarily posts)
permalink: /whats-new/updates/:year/:month/:day/:title/
google_analytics_ua: UA-48605964-43
# this ensure that posts with future dates are published
future: true

baseurl: /nasawds-site

encoding: utf-8

incremental_regeneration_fixer:
  interdependent_files:
    - "_components/colors/*"
    - "_components/form-controls/*"
    - "_components/form-templates/*"
    - "_components/typography/*"

jekyll_get:
  - data: releases
    json: 'https://api.github.com/repos/nasa/nasawds/releases'
  - data: contributing
    json: 'https://api.github.com/repos/uswds/uswds/contents/CONTRIBUTING.md'
    decode_content: true
  - data: standards-sites
    json: 'https://api.github.com/repos/uswds/uswds/contents/WHO_IS_USING_USWDS.md'
    decode_content: true

repos:
- name: NASA Web Design System
  description: Main repository for the NASA Web Design System package
  url: https://github.com/nasa/nasawds
- name: NASA Web Design System Documentation
  description: Documentation for the NASA Web Design System
  url: https://github.com/nasa/nasawds-site
- name: U.S. Web Design System Assets
  description: U.S. Web Design System visual design assets
  url: https://github.com/uswds/uswds-assets

sass:
  load_paths:
    - css
    - assets/css

collections:
  components:
    output: true
    permalink: /:path/

defaults:
  - scope:
      path: ''
      type: components
    values:
      layout: component
  - scope:
      path: ''
      type: posts
    values:
      layout: post

# Build settings
markdown: RedcarpetExtender
redcarpet:
  extensions:
    - smart
    - tables
    - with_toc_data # automatic heading ids

gems:
  - jekyll-redirect-from

exclude:
- ".ruby-version"
- ".sass-cache"
- CONTRIBUTING.md
- Gemfile
- Gemfile.lock
- LICENSE.md
- README.md
- "config/*"
- "js/*"
- manifest.yml
- node_modules
- package.json
- "vendor/*"
- gulpfile.js
- circle.yml
