version: 2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.3-node-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-gem-cache-{{ checksum "Gemfile.lock" }}
            - v1-gem-cache
      - run:
          name: Install ruby dependencies
          command: bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_cache:
          key: v1-gem-cache-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - restore_cache:
          keys:
            - v1-node-cache-{{ checksum "yarn.lock" }}
            - v1-node-cache
      - run:
          name: Install node dependencies
          command: npm install --ignore-scripts --verbose
      - save_cache:
          key: v1-node-cache-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run:
          name: Build site files
          command: npm run build
      - run:
          name: Run test
          command: npm test
      - run:
          name: Checking build
          command: ls -agolf _site/
  deploy:
    docker:
      - image: circleci/ruby:2.3-node-browsers
    steps:
      - add_ssh_keys:
          fingerprints:
            - "21:a8:a1:3d:73:93:88:ec:78:1f:ab:61:0a:fd:d4:4a"
      - run: |
          git config --global user.email "$GH_EMAIL" > /dev/null 2>&1
          git config --global user.name "$GH_NAME" > /dev/null 2>&1
      - checkout
      - run:
          name: Install ruby dependencies
          command: bundle install
      - run:
          name: Install node dependencies
          command: npm install
      - run:
          name: Build site files
          command: npm run build
      - run:
          name: Deploy gh-pages
          command: npm run deploy
        
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore: gh-pages
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master